name: Deploy Angular Frontend to ECR and ECS

on:
  push:
    branches:
      - main
      - testing

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
          
      - name: Create Angular environment files
        run: |
          mkdir -p src/environments

          cat <<EOF > src/environments/environment.ts
          export const environment = {
            production: false,
            apiUrl: '',
          }
          EOF

          echo "${{ secrets.ENVIRONMENT_PROD_TS }}" > src/environments/environment.prod.ts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: qrcode-frontend-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          echo "Building Angular app and Docker image..."
          npm install
          npm run build --prod

          docker build -t $IMAGE_URI .

          echo "Pushing image..."
          docker push $IMAGE_URI


      - name: Clone Terraform Repository
        uses: actions/checkout@v4
        with:
          repository: Franz-James-Kaba/QR-Code-Frontend_Architecture
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: terraform-infra
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0
      
      - name: Generate terraform.tfvars file
        working-directory: terraform-infra
        run: |
          cat <<EOF > terraform.tfvars
          vpc_id     = "${{ secrets.VPC_ID }}"
          subnet_ids = ["${{ secrets.SUBNET_ID_1 }}", "${{ secrets.SUBNET_ID_2 }}"]
          image_uri  = "${IMAGE_URI}"
          EOF

      - name: Apply Terraform
        working-directory: terraform-infra
        run: |
          terraform init
          terraform apply -var-file=terraform.tfvars -auto-approve

